"""initial schema

Revision ID: 486cf6bc06e4
Revises: 
Create Date: 2026-05-16 09:46:07.998077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486cf6bc06e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_phone', sa.String(length=32), nullable=False),
    sa.Column('doctor_id', sa.String(length=128), nullable=False),
    sa.Column('doctor_name', sa.String(length=256), nullable=False),
    sa.Column('doctor_specialty', sa.String(length=64), nullable=False),
    sa.Column('doctor_clinic_name', sa.String(length=256), nullable=False),
    sa.Column('doctor_address', sa.Text(), nullable=False),
    sa.Column('doctor_phone', sa.String(length=32), nullable=False),
    sa.Column('doctor_distance_m', sa.Integer(), nullable=True),
    sa.Column('slot_start', sa.DateTime(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_user_phone'), ['user_phone'], unique=False)

    op.create_table('users',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('home_address_raw', sa.Text(), nullable=False),
    sa.Column('home_city', sa.String(length=128), nullable=True),
    sa.Column('home_postal_code', sa.String(length=16), nullable=True),
    sa.Column('home_country', sa.String(length=8), nullable=False),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lng', sa.Float(), nullable=True),
    sa.Column('insurer', sa.String(length=32), nullable=False),
    sa.Column('insurer_username_enc', sa.Text(), nullable=False),
    sa.Column('insurer_password_enc', sa.Text(), nullable=False),
    sa.Column('preferred_times', sa.String(length=16), nullable=False),
    sa.Column('excluded_days_csv', sa.String(length=128), nullable=False),
    sa.Column('max_weeks_out', sa.Integer(), nullable=False),
    sa.Column('travel_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('blocked_windows_json', sa.Text(), nullable=False),
    sa.Column('google_calendar_token_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_user_phone'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
