"""drop blocked_windows_json from users

Revision ID: 9409aca91a75
Revises: bbd6c15d3f59
Create Date: 2026-05-16 19:28:09.645106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9409aca91a75'
down_revision: Union[str, Sequence[str], None] = 'bbd6c15d3f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blocked_windows_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # server_default makes the re-added column safe on populated tables.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'blocked_windows_json',
                sa.TEXT(),
                nullable=False,
                server_default='[]',
            )
        )
