"""add onboarding_drafts and credentials_tokens tables

Revision ID: bbd6c15d3f59
Revises: 486cf6bc06e4
Create Date: 2026-05-16 11:43:45.253066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd6c15d3f59'
down_revision: Union[str, Sequence[str], None] = '486cf6bc06e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('credentials_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_credentials_tokens_phone', ['phone'], unique=False)

    op.create_table('onboarding_drafts',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('home_address', sa.Text(), nullable=True),
    sa.Column('insurer', sa.String(length=32), nullable=True),
    sa.Column('preferred_times', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_drafts')
    with op.batch_alter_table('credentials_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_credentials_tokens_phone')

    op.drop_table('credentials_tokens')
    # ### end Alembic commands ###
